#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectCourseSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RemoteUSTC")]
	public partial class RemoteDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertrCourse(rCourse instance);
    partial void UpdaterCourse(rCourse instance);
    partial void DeleterCourse(rCourse instance);
    partial void InsertrMajor(rMajor instance);
    partial void UpdaterMajor(rMajor instance);
    partial void DeleterMajor(rMajor instance);
    partial void InsertrMajorType(rMajorType instance);
    partial void UpdaterMajorType(rMajorType instance);
    partial void DeleterMajorType(rMajorType instance);
    partial void InsertrStudent(rStudent instance);
    partial void UpdaterStudent(rStudent instance);
    partial void DeleterStudent(rStudent instance);
    partial void InsertrCoursePlan(rCoursePlan instance);
    partial void UpdaterCoursePlan(rCoursePlan instance);
    partial void DeleterCoursePlan(rCoursePlan instance);
    #endregion
		
		public RemoteDatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["remoteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RemoteDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RemoteDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RemoteDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RemoteDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<rCourse> rCourse
		{
			get
			{
				return this.GetTable<rCourse>();
			}
		}
		
		public System.Data.Linq.Table<rMajor> rMajor
		{
			get
			{
				return this.GetTable<rMajor>();
			}
		}
		
		public System.Data.Linq.Table<rMajorType> rMajorType
		{
			get
			{
				return this.GetTable<rMajorType>();
			}
		}
		
		public System.Data.Linq.Table<rStudent> rStudent
		{
			get
			{
				return this.GetTable<rStudent>();
			}
		}
		
		public System.Data.Linq.Table<rCoursePlan> rCoursePlan
		{
			get
			{
				return this.GetTable<rCoursePlan>();
			}
		}
		
		public System.Data.Linq.Table<ElectiveStudent> ElectiveStudent
		{
			get
			{
				return this.GetTable<ElectiveStudent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rCourse")]
	public partial class rCourse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ObjectID;
		
		private string _CourseID;
		
		private string _CourseName;
		
		private string _TheoryHours;
		
		private double _Credit;
		
		private string _writer;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectIDChanging(System.Guid value);
    partial void OnObjectIDChanged();
    partial void OnCourseIDChanging(string value);
    partial void OnCourseIDChanged();
    partial void OnCourseNameChanging(string value);
    partial void OnCourseNameChanged();
    partial void OnTheoryHoursChanging(string value);
    partial void OnTheoryHoursChanged();
    partial void OnCreditChanging(double value);
    partial void OnCreditChanged();
    partial void OnwriterChanging(string value);
    partial void OnwriterChanged();
    #endregion
		
		public rCourse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this.OnObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectID = value;
					this.SendPropertyChanged("ObjectID");
					this.OnObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this.OnCourseIDChanging(value);
					this.SendPropertyChanging();
					this._CourseID = value;
					this.SendPropertyChanged("CourseID");
					this.OnCourseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseName
		{
			get
			{
				return this._CourseName;
			}
			set
			{
				if ((this._CourseName != value))
				{
					this.OnCourseNameChanging(value);
					this.SendPropertyChanging();
					this._CourseName = value;
					this.SendPropertyChanged("CourseName");
					this.OnCourseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheoryHours", DbType="NVarChar(50)")]
		public string TheoryHours
		{
			get
			{
				return this._TheoryHours;
			}
			set
			{
				if ((this._TheoryHours != value))
				{
					this.OnTheoryHoursChanging(value);
					this.SendPropertyChanging();
					this._TheoryHours = value;
					this.SendPropertyChanged("TheoryHours");
					this.OnTheoryHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Credit", DbType="Float NOT NULL")]
		public double Credit
		{
			get
			{
				return this._Credit;
			}
			set
			{
				if ((this._Credit != value))
				{
					this.OnCreditChanging(value);
					this.SendPropertyChanging();
					this._Credit = value;
					this.SendPropertyChanged("Credit");
					this.OnCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_writer", DbType="NVarChar(400)")]
		public string writer
		{
			get
			{
				return this._writer;
			}
			set
			{
				if ((this._writer != value))
				{
					this.OnwriterChanging(value);
					this.SendPropertyChanging();
					this._writer = value;
					this.SendPropertyChanged("writer");
					this.OnwriterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rMajor")]
	public partial class rMajor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _MajorID;
		
		private string _MajorName;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMajorIDChanging(System.Guid value);
    partial void OnMajorIDChanged();
    partial void OnMajorNameChanging(string value);
    partial void OnMajorNameChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public rMajor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid MajorID
		{
			get
			{
				return this._MajorID;
			}
			set
			{
				if ((this._MajorID != value))
				{
					this.OnMajorIDChanging(value);
					this.SendPropertyChanging();
					this._MajorID = value;
					this.SendPropertyChanged("MajorID");
					this.OnMajorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MajorName
		{
			get
			{
				return this._MajorName;
			}
			set
			{
				if ((this._MajorName != value))
				{
					this.OnMajorNameChanging(value);
					this.SendPropertyChanging();
					this._MajorName = value;
					this.SendPropertyChanged("MajorName");
					this.OnMajorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(200)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rMajorType")]
	public partial class rMajorType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _MajorTypeID;
		
		private string _MajorTypeName;
		
		private System.Guid _MajorID;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMajorTypeIDChanging(System.Guid value);
    partial void OnMajorTypeIDChanged();
    partial void OnMajorTypeNameChanging(string value);
    partial void OnMajorTypeNameChanged();
    partial void OnMajorIDChanging(System.Guid value);
    partial void OnMajorIDChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public rMajorType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorTypeID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid MajorTypeID
		{
			get
			{
				return this._MajorTypeID;
			}
			set
			{
				if ((this._MajorTypeID != value))
				{
					this.OnMajorTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MajorTypeID = value;
					this.SendPropertyChanged("MajorTypeID");
					this.OnMajorTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorTypeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MajorTypeName
		{
			get
			{
				return this._MajorTypeName;
			}
			set
			{
				if ((this._MajorTypeName != value))
				{
					this.OnMajorTypeNameChanging(value);
					this.SendPropertyChanging();
					this._MajorTypeName = value;
					this.SendPropertyChanged("MajorTypeName");
					this.OnMajorTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MajorID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid MajorID
		{
			get
			{
				return this._MajorID;
			}
			set
			{
				if ((this._MajorID != value))
				{
					this.OnMajorIDChanging(value);
					this.SendPropertyChanging();
					this._MajorID = value;
					this.SendPropertyChanged("MajorID");
					this.OnMajorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(300)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rStudent")]
	public partial class rStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _RStudentID;
		
		private string _RStuNo;
		
		private string _RName;
		
		private byte _RSex;
		
		private System.Guid _RMajor;
		
		private System.Guid _RMajorType;
		
		private string _RNation;
		
		private string _RStudentProperty;
		
		private string _RInSchoolMode;
		
		private System.DateTime _SchoolYear;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRStudentIDChanging(System.Guid value);
    partial void OnRStudentIDChanged();
    partial void OnRStuNoChanging(string value);
    partial void OnRStuNoChanged();
    partial void OnRNameChanging(string value);
    partial void OnRNameChanged();
    partial void OnRSexChanging(byte value);
    partial void OnRSexChanged();
    partial void OnRMajorChanging(System.Guid value);
    partial void OnRMajorChanged();
    partial void OnRMajorTypeChanging(System.Guid value);
    partial void OnRMajorTypeChanged();
    partial void OnRNationChanging(string value);
    partial void OnRNationChanged();
    partial void OnRStudentPropertyChanging(string value);
    partial void OnRStudentPropertyChanged();
    partial void OnRInSchoolModeChanging(string value);
    partial void OnRInSchoolModeChanged();
    partial void OnSchoolYearChanging(System.DateTime value);
    partial void OnSchoolYearChanged();
    #endregion
		
		public rStudent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStudentID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RStudentID
		{
			get
			{
				return this._RStudentID;
			}
			set
			{
				if ((this._RStudentID != value))
				{
					this.OnRStudentIDChanging(value);
					this.SendPropertyChanging();
					this._RStudentID = value;
					this.SendPropertyChanged("RStudentID");
					this.OnRStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStuNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RStuNo
		{
			get
			{
				return this._RStuNo;
			}
			set
			{
				if ((this._RStuNo != value))
				{
					this.OnRStuNoChanging(value);
					this.SendPropertyChanging();
					this._RStuNo = value;
					this.SendPropertyChanged("RStuNo");
					this.OnRStuNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string RName
		{
			get
			{
				return this._RName;
			}
			set
			{
				if ((this._RName != value))
				{
					this.OnRNameChanging(value);
					this.SendPropertyChanging();
					this._RName = value;
					this.SendPropertyChanged("RName");
					this.OnRNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSex", DbType="TinyInt NOT NULL")]
		public byte RSex
		{
			get
			{
				return this._RSex;
			}
			set
			{
				if ((this._RSex != value))
				{
					this.OnRSexChanging(value);
					this.SendPropertyChanging();
					this._RSex = value;
					this.SendPropertyChanged("RSex");
					this.OnRSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMajor", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RMajor
		{
			get
			{
				return this._RMajor;
			}
			set
			{
				if ((this._RMajor != value))
				{
					this.OnRMajorChanging(value);
					this.SendPropertyChanging();
					this._RMajor = value;
					this.SendPropertyChanged("RMajor");
					this.OnRMajorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMajorType", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RMajorType
		{
			get
			{
				return this._RMajorType;
			}
			set
			{
				if ((this._RMajorType != value))
				{
					this.OnRMajorTypeChanging(value);
					this.SendPropertyChanging();
					this._RMajorType = value;
					this.SendPropertyChanged("RMajorType");
					this.OnRMajorTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNation", DbType="NVarChar(50)")]
		public string RNation
		{
			get
			{
				return this._RNation;
			}
			set
			{
				if ((this._RNation != value))
				{
					this.OnRNationChanging(value);
					this.SendPropertyChanging();
					this._RNation = value;
					this.SendPropertyChanged("RNation");
					this.OnRNationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RStudentProperty", DbType="NVarChar(50)")]
		public string RStudentProperty
		{
			get
			{
				return this._RStudentProperty;
			}
			set
			{
				if ((this._RStudentProperty != value))
				{
					this.OnRStudentPropertyChanging(value);
					this.SendPropertyChanging();
					this._RStudentProperty = value;
					this.SendPropertyChanged("RStudentProperty");
					this.OnRStudentPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RInSchoolMode", DbType="NVarChar(50)")]
		public string RInSchoolMode
		{
			get
			{
				return this._RInSchoolMode;
			}
			set
			{
				if ((this._RInSchoolMode != value))
				{
					this.OnRInSchoolModeChanging(value);
					this.SendPropertyChanging();
					this._RInSchoolMode = value;
					this.SendPropertyChanged("RInSchoolMode");
					this.OnRInSchoolModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolYear", DbType="DateTime NOT NULL")]
		public System.DateTime SchoolYear
		{
			get
			{
				return this._SchoolYear;
			}
			set
			{
				if ((this._SchoolYear != value))
				{
					this.OnSchoolYearChanging(value);
					this.SendPropertyChanging();
					this._SchoolYear = value;
					this.SendPropertyChanged("SchoolYear");
					this.OnSchoolYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rCoursePlan")]
	public partial class rCoursePlan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ObjectID;
		
		private string _ClassID;
		
		private string _CourseID;
		
		private string _CourseName;
		
		private string _TeacherName;
		
		private string _DetailLocation;
		
		private string _TimeAndRoom;
		
		private System.DateTime _ElectiveStartTime;
		
		private System.DateTime _ElectiveEndTime;
		
		private System.DateTime _BackCourseEndTime;
		
		private int _MaxNumber;
		
		private string _OptionalProfessional;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnObjectIDChanging(System.Guid value);
    partial void OnObjectIDChanged();
    partial void OnClassIDChanging(string value);
    partial void OnClassIDChanged();
    partial void OnCourseIDChanging(string value);
    partial void OnCourseIDChanged();
    partial void OnCourseNameChanging(string value);
    partial void OnCourseNameChanged();
    partial void OnTeacherNameChanging(string value);
    partial void OnTeacherNameChanged();
    partial void OnDetailLocationChanging(string value);
    partial void OnDetailLocationChanged();
    partial void OnTimeAndRoomChanging(string value);
    partial void OnTimeAndRoomChanged();
    partial void OnElectiveStartTimeChanging(System.DateTime value);
    partial void OnElectiveStartTimeChanged();
    partial void OnElectiveEndTimeChanging(System.DateTime value);
    partial void OnElectiveEndTimeChanged();
    partial void OnBackCourseEndTimeChanging(System.DateTime value);
    partial void OnBackCourseEndTimeChanged();
    partial void OnMaxNumberChanging(int value);
    partial void OnMaxNumberChanged();
    partial void OnOptionalProfessionalChanging(string value);
    partial void OnOptionalProfessionalChanged();
    #endregion
		
		public rCoursePlan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this.OnObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectID = value;
					this.SendPropertyChanged("ObjectID");
					this.OnObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="NVarChar(50)")]
		public string ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this.OnClassIDChanging(value);
					this.SendPropertyChanging();
					this._ClassID = value;
					this.SendPropertyChanged("ClassID");
					this.OnClassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this.OnCourseIDChanging(value);
					this.SendPropertyChanging();
					this._CourseID = value;
					this.SendPropertyChanged("CourseID");
					this.OnCourseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseName
		{
			get
			{
				return this._CourseName;
			}
			set
			{
				if ((this._CourseName != value))
				{
					this.OnCourseNameChanging(value);
					this.SendPropertyChanging();
					this._CourseName = value;
					this.SendPropertyChanged("CourseName");
					this.OnCourseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TeacherName
		{
			get
			{
				return this._TeacherName;
			}
			set
			{
				if ((this._TeacherName != value))
				{
					this.OnTeacherNameChanging(value);
					this.SendPropertyChanging();
					this._TeacherName = value;
					this.SendPropertyChanged("TeacherName");
					this.OnTeacherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailLocation", DbType="NVarChar(50)")]
		public string DetailLocation
		{
			get
			{
				return this._DetailLocation;
			}
			set
			{
				if ((this._DetailLocation != value))
				{
					this.OnDetailLocationChanging(value);
					this.SendPropertyChanging();
					this._DetailLocation = value;
					this.SendPropertyChanged("DetailLocation");
					this.OnDetailLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeAndRoom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TimeAndRoom
		{
			get
			{
				return this._TimeAndRoom;
			}
			set
			{
				if ((this._TimeAndRoom != value))
				{
					this.OnTimeAndRoomChanging(value);
					this.SendPropertyChanging();
					this._TimeAndRoom = value;
					this.SendPropertyChanged("TimeAndRoom");
					this.OnTimeAndRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectiveStartTime", DbType="DateTime NOT NULL")]
		public System.DateTime ElectiveStartTime
		{
			get
			{
				return this._ElectiveStartTime;
			}
			set
			{
				if ((this._ElectiveStartTime != value))
				{
					this.OnElectiveStartTimeChanging(value);
					this.SendPropertyChanging();
					this._ElectiveStartTime = value;
					this.SendPropertyChanged("ElectiveStartTime");
					this.OnElectiveStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElectiveEndTime", DbType="DateTime NOT NULL")]
		public System.DateTime ElectiveEndTime
		{
			get
			{
				return this._ElectiveEndTime;
			}
			set
			{
				if ((this._ElectiveEndTime != value))
				{
					this.OnElectiveEndTimeChanging(value);
					this.SendPropertyChanging();
					this._ElectiveEndTime = value;
					this.SendPropertyChanged("ElectiveEndTime");
					this.OnElectiveEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BackCourseEndTime", DbType="DateTime NOT NULL")]
		public System.DateTime BackCourseEndTime
		{
			get
			{
				return this._BackCourseEndTime;
			}
			set
			{
				if ((this._BackCourseEndTime != value))
				{
					this.OnBackCourseEndTimeChanging(value);
					this.SendPropertyChanging();
					this._BackCourseEndTime = value;
					this.SendPropertyChanged("BackCourseEndTime");
					this.OnBackCourseEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxNumber", DbType="Int NOT NULL")]
		public int MaxNumber
		{
			get
			{
				return this._MaxNumber;
			}
			set
			{
				if ((this._MaxNumber != value))
				{
					this.OnMaxNumberChanging(value);
					this.SendPropertyChanging();
					this._MaxNumber = value;
					this.SendPropertyChanged("MaxNumber");
					this.OnMaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionalProfessional", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OptionalProfessional
		{
			get
			{
				return this._OptionalProfessional;
			}
			set
			{
				if ((this._OptionalProfessional != value))
				{
					this.OnOptionalProfessionalChanging(value);
					this.SendPropertyChanging();
					this._OptionalProfessional = value;
					this.SendPropertyChanged("OptionalProfessional");
					this.OnOptionalProfessionalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ElectiveStudent")]
	public partial class ElectiveStudent
	{
		
		private System.Guid _ObjectID;
		
		private string _StudentID;
		
		private string _StudentName;
		
		private string _CourseID;
		
		private string _Year;
		
		public ElectiveStudent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this._ObjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this._StudentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this._StudentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
